-- Crear tabla para el historial de chat de los bots
CREATE TABLE IF NOT EXISTS chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  role TEXT NOT NULL, -- 'user' o 'model'
  content JSONB NOT NULL, -- El contenido estructurado (parts, etc)
  agent TEXT NOT NULL, -- 'secretaria', 'alumbra', 'powertrader'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Índices para búsquedas rápidas por chat
CREATE INDEX IF NOT EXISTS idx_chat_history_id ON chat_history(chat_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_agent ON chat_history(agent);

-- Habilitar RLS (Seguridad a nivel de fila)
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Política para que el rol service_role tenga acceso total (la función la usa así)
CREATE POLICY "Servicio total en historial" ON chat_history FOR ALL USING (true);
